### ISSUE TITLE
Missing "types"/"typings": "./types/index.d.ts" in package.json

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [yoavniran/cypress-intercept-formdata#1]
Hi, thanks so much for this great package! @jakemhiller and now I are using it and enjoying it.

One small note about the TypeScript types: because they're at `./types/index.d.ts`, which isn't the `./index.d.ts` TypeScript tries by default, they can't be found by TypeScript projects by default. Adding this line to the `package.json` would fix that:

```json
"types": "./types/index.d.ts"
```

Without it (for SEO on this issue), you get:

```
cy.wait('@someApi').interceptFormData((formData) => {
// Property 'interceptFormData' does not exist on type 'Chainable<Interception>'.
```

**Comment by yoavniran** [comment]
@JoshuaKGoldberg thanks! I was sure I'd added it 🤦
