### ISSUE TITLE
Snake case property names are not supported

### ISSUE THREAD

**Issue by realtomaszkula** [yoavniran/cypress-intercept-formdata#10]
interceptFormData does not return property names that have a dash in them.

For example, if I try to submit this object:

```
{ 'form-name': 'myForm' }
```

The formData in the callback will not include the 'form-name' property.

```javascript
cy.wait('@myRequest').interceptFormData((formData) => {
  // this will fail, formData['form-name'] will be undefined
  expect(formData['form-name']).to.eq('myForm');
});
```

The issue stems from this RegExp:
https://github.com/yoavniran/cypress-intercept-formdata/blob/ef9eb611842cf806a781b70ebadf18d8e0968cf0/src/parsers/genericFieldParser.js#L4

**Comment by yoavniran** [comment]
hey @zetsnotdead 
I will create a fix for this shortly.

BTW, this is actually `kebab-case`. This is `snake_case`. I will add support for both

**Comment by realtomaszkula** [comment]
Ah, yeah, got that two mixed up :) 

Thanks a lot for taking a look. The lib is great :)

**Comment by yoavniran** [comment]
@zetsnotdead - 0.5.1 is now out with the fix.
