### ISSUE TITLE
Is it possible to get the uploaded file data?

### ISSUE THREAD

**Issue by willm** [yoavniran/cypress-intercept-formdata#11]
I've seen that this library can read the form fields and the file paths, but is it possible to actually inspect the uploaded file? My application creates a file in the browser and I would like to check that it is valid.

**Comment by yoavniran** [comment]
Hey @willm 
currently thats not possible. The request is handed from cypress as a blob of text.
I will check how to add this as an option

**Comment by goatfryed** [comment]
Hey, I came here looking for the same thing

Compare this formdata

```
------WebKitFormBoundaryqoMoGA4BPondHpYB
Content-Disposition: form-data; name="subject"

Showcases
------WebKitFormBoundaryqoMoGA4BPondHpYB
Content-Disposition: form-data; name="attachments"; filename="sample.pdf"
Content-Type: application/pdf

%PDF-1.1
%¥±ë

1 0 obj
  << /Type /Catalog
     /Pages 2 0 R
  >>
endobj

2 0 obj
  << /Type /Pages
     /Kids [3 0 R]
     /Count 1
     /MediaBox [0 0 300 144]
  >>
endobj

3 0 obj
  <<  /Type /Page
      /Parent 2 0 R
      /Resources
       << /Font
           << /F1
               << /Type /Font
                  /Subtype /Type1
                  /BaseFont /Times-Roman
               >>
           >>
       >>
      /Contents 4 0 R
  >>
endobj

4 0 obj
  << /Length 55 >>
stream
  BT
    /F1 18 Tf
    0 0 Td
    (Hello World) Tj
  ET
endstream
endobj

xref
0 5
0000000000 65535 f 
0000000018 00000 n 
0000000077 00000 n 
0000000178 00000 n 
0000000457 00000 n 
trailer
  <<  /Root 1 0 R
      /Size 5
  >>
startxref
565
%%EOF
------WebKitFormBoundaryqoMoGA4BPondHpYB
Content-Disposition: form-data; name="attachments"; filename="sample.crt"
Content-Type: application/x-x509-ca-cert

test
------WebKitFormBoundaryqoMoGA4BPondHpYB
Content-Disposition: form-data; name="text"

Hello, Chuck!
------WebKitFormBoundaryqoMoGA4BPondHpYB--
```

Currently, this gets transformed to
```js
{
  subject: "Showcases",
  attachments: "sample.crt",
}
```

So we don't have access to the contents and we also don't have access to multiple attachments.

Maybe, we could react to the filename attribute and create a map of filename to TypedArrayBuffer? I'm aware that this would introduce a breaking change, but since the attachments don't consider multiples at the moment, this might be worth it.

If this approach sounds fine, I'd be willing to contribute.

**Comment by yoavniran** [comment]
hey @goatfryed 
ill take a look and think how best to go about adding. ill add my thoughts here

**Comment by yoavniran** [comment]
@willm @goatfryed 
Version [0.6.0](https://github.com/yoavniran/cypress-intercept-formdata/releases/tag/v0.6.0) is out and supports multiple files AND loading file content (see [docs](https://github.com/yoavniran/cypress-intercept-formdata#file-content))

One caveat, I think there's a limit to what can be done in the browser in terms of loading the binary content of the file from the multipart body buffer. For example, I wasnt able to get a valid image file back from the jpg file (binary) I uploaded.
If you know how to better do that on the client-side I'd be happy to improve.
