### ISSUE TITLE
Regex to match name param in the boundary of form data doesn't work with dot

### ISSUE THREAD

**Issue by Lilja** [yoavniran/cypress-intercept-formdata#12]
https://regex101.com/r/dBTNtc/1

We send data to our hubspot as `TICKET.metadata`-etc. The regex in `genericFieldParser` doesn't take that into account.

**Comment by yoavniran** [comment]
thanks @Lilja 
will try and have a fix real soon

**Comment by yoavniran** [comment]
version 0.5.2 should now fix this
