### ISSUE TITLE
Arrays in Form-Data missing

### ISSUE THREAD

**Issue by FlyingHelix** [yoavniran/cypress-intercept-formdata#8]
We have multiple arrays in our Formdata that show up in the Network Request in the dev tools like this:
```
skills[0][id]: 28
skills[0][levelID]: 6
skills[1][id]: 31
skills[1][levelID]: 6
skills[2][id]: 51
skills[2][levelID]: 6
```
but they are completely missing when logging the intercepted Form Data and looking at it in the console.
Are arrays in Form Data just not supported or is that actually a Bug?

my cypress version is 9.6.1 and cypress-intercept-formdata is 0.4.0

**Comment by yoavniran** [comment]
Hey @FlyingHelix 
That's currently unsupported but Id like to add it to CIFD's next version.
How are you appending the objects from each array item so they appear in the way you described? 
Please share the code that calls `formData.append()`.

thanks

**Comment by FlyingHelix** [comment]
Hey @yoavniran 
good to hear!
at the moment we use the npm module object-to-formdata and our code is something like this:
```
const formDataPayload: FormData = serialize(payload, { indices: true, nullsAsUndefineds: true });

sendRequest(id: number, payload: FormData) {
    return this.http.post(`${environment.apiBaseUrl}/linkWith/${id}/function`, payload);
  }
```

I hope that hepls.

**Comment by yoavniran** [comment]
Good news @FlyingHelix 
[version 0.5.0](https://github.com/yoavniran/cypress-intercept-formdata/releases/tag/v0.5.0) now out with support for object-to-formdata fields
Please give it a try and let me know

**Comment by FlyingHelix** [comment]
thank you, it works beautifully!
